site_name: Engenharia de Dados SATC
site_description: Documentacao do projeto <nome do projeto>
site_author: Edrik Steiner - Eduardo Scalco - Eryc Jacinto - Igor Steiner - Taylor Teixeira
site_url: https://taylorteixeira.github.io/projeto-ed-satc

repo_name: projeto-ed-satc
repo_url: https://github.com/taylorteixeira/projeto-ed-satc
edit_uri: edit/master/docs/

docs_dir: docs

nav:
  - Início: index.md
  - Dashboard: projeto_ed_satc/dashboard.md
  - Modelo Relacional: modelo_relacional.md
  - Infraestrutura como Código (IaC): 
      - Visão Geral: iac/index.md
      - Azure Data Lake Storage (Terraform): iac/adls.md
      - Azure Databricks Workspace (Provisionamento): iac/databricks_provisioning.md
  - Projeto Principal (`projeto_ed_satc`):
      - Visão Geral: projeto_ed_satc/index.md
      - Script ELT MongoDB: projeto_ed_satc/mongo_script.md
      - Notebooks Databricks: projeto_ed_satc/databricks_notebooks.md

theme:
  name: material
  palette:
    primary: blue
    accent: light-blue
  language: pt
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.paging
    - navigation.expand
    - navigation.top
    - navigation.sidebar
    - navigation.next-prev
    - navigation.toc
    - navigation.scrollspy
    - search
  icon:
    repo: fontawesome/brands/github




copyright: Copyright &copy; 2025 - <a href="#" target="_blank"><b>Taylor Vargas Teixeira</b></a> - Todos os direitos reservados.


markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - attr_list
  - def_list
  - admonition    
  - pymdownx.superfences  
  - pymdownx.inlinehilite 
  - pymdownx.highlight
  - pymdownx.tasklist

plugins:
  - search  
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_signature: true  
